filesys.c: Copy in freeblk()
This fixes the following build error:

<snip>
fs/filesys.c:61: Error: Call to undeclared function 'freeblk'
</snip>

But introduces these:

<snip>
fs/filesys.c:89: Error: Call to undeclared function 'bread'
fs/filesys.c:92: Error: Call to undeclared function 'brelse'
fs/filesys.c:95: Error: Call to undeclared function 'blk_free'
</snip>