filesys.c: Fix missing bzero() declaration
This fixes the following build error:

<snip>
fs/filesys.c:69: Error: Call to undeclared function 'bzero'
</snip>