uzi-nes-utils/linux_fs.h: Include unix.h
While working on fsutil.c, I caught the following build error:

<snip>
gcc -I/home/athorlton/code/uzics-build//uzi-nes-port/include -o fsutil fsutil.c linux_fs.o
In file included from linux_fs.h:4,
                 from fsutil.c:5:
linux_fs.h:16:46: error: unknown type name ‘filesys’
   16 | #define DUMMY_BLOCKSIZE BLOCKSIZE + offsetof(filesys, s_nfree)
      |                                              ^~~~~~~
fsutil.c:8:13: note: in expansion of macro ‘DUMMY_BLOCKSIZE’
    8 | char sb_buf[DUMMY_BLOCKSIZE] =  { 0 };
      |             ^~~~~~~~~~~~~~~
make: *** [Makefile:20: fsutil] Error 1
</snip>

I hadn't noticed this problem before, because all the files that include
linux_fs.h include unix.h first.  Fix this before checking in fsutil
stuff, since it's technically unrelated.