filesys: Pull in i_alloc
This causes the following build error:

<snip>
fs/filesys.c:308: Error: Call to undeclared function '_sync'
</snip>

I'm checkpointing this before pulling in more, because I think _sync
will change a good bit, since there's almost nothing else in scall1.c
yet.