process: Begin working on newproc()
The code currently doesn't compile because of these issues:

<snip>
kernel/process.c:29: Error: Call to undeclared function 'rdtime'
kernel/process.c:30: Error: Call to undeclared function 'i_ref'
</snip>

rdtime() isn't trivial to implement, so I'm setting a checkpoint here
before moving further.