filesys.c: Pull in f_trunc()
This fixes the following build error:

<snip>
fs/filesys.c:34: Error: Call to undeclared function 'f_trunc'
</snip>

But introduces these two:

<snip>
fs/filesys.c:60: Error: Call to undeclared function 'freeblk'
fs/filesys.c:69: Error: Call to undeclared function 'bzero'
</snip>