filesys.c: Pull in magic()
This fixes the following build error:

<snip>
fs/filesys.c:19: Error: Call to undeclared function 'magic'
</snip>

Note that I've used a forward declaration instead of adding the
prototype to the header.