filesys.c: Fix missing wakeup declaration
This fixes the following build error:

<snip>
fs/filesys.c:27: Error: Call to undeclared function 'wakeup'
</snip>