utils/fs/fsutil: Work towards fixing remaining build issues
This is what's left here:

<snip>
gcc -g -o fsutil fsutil_src/fsutil_all.o linux_fs.o
/usr/bin/ld: fsutil_src/fsutil_all.o(fsutil.o): in function `fs_init':
/home/athorlton/code/uzi-build/uzi-nes-utils/fs/fsutil_src/fsutil.c:151: undefined reference to `fmount'
/usr/bin/ld: /home/athorlton/code/uzi-build/uzi-nes-utils/fs/fsutil_src/fsutil.c:154: undefined reference to `i_open'
/usr/bin/ld: /home/athorlton/code/uzi-build/uzi-nes-utils/fs/fsutil_src/fsutil.c:156: undefined reference to `i_ref'
/usr/bin/ld: /home/athorlton/code/uzi-build/uzi-nes-utils/fs/fsutil_src/fsutil.c:157: undefined reference to `rdtime'
/usr/bin/ld: fsutil_src/fsutil_all.o(linux_ls.o): in function `ls':
/home/athorlton/code/uzi-build/uzi-nes-utils/fs/fsutil_src/linux_ls.c:12: undefined reference to `_open'
/usr/bin/ld: /home/athorlton/code/uzi-build/uzi-nes-utils/fs/fsutil_src/linux_ls.c:29: undefined reference to `_stat'
/usr/bin/ld: /home/athorlton/code/uzi-build/uzi-nes-utils/fs/fsutil_src/linux_ls.c:18: undefined reference to `_read'
/usr/bin/ld: /home/athorlton/code/uzi-build/uzi-nes-utils/fs/fsutil_src/linux_ls.c:46: undefined reference to `_close'
collect2: error: ld returned 1 exit status
make: *** [Makefile:28: fsutil] Error 1
</snip>

These require a bit more work.