kernel/process.c: Start porting unix()
This won't port over cleanly because the indirect function calls don't
play nice in cc65:

<snip>
kernel/process.c:439: Error: Undeclared identifier 'disp_tab'
kernel/process.c:439: Error: Subscripted value is neither array nor pointer
kernel/process.c:439: Error: Illegal indirection
kernel/process.c:439: Error: Illegal function call
</snip>

For now just comment out the offending line, since we're going to have
to handle the dispatch totally differently anyway, to account for all
the banked calls.